-- ==============================================================================
-- RESTA : CRÉATION DE LA TABLE DES MESSAGES & ACTIVATION DU TEMPS RÉEL (REALTIME)
-- ==============================================================================
-- Exécutez ce script dans l'Éditeur SQL de votre tableau de bord Supabase
-- (Dashboard Supabase > SQL Editor > New query > Run)

-- 1. Création de la table des messages
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id TEXT NOT NULL,
    client_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    client_nom TEXT DEFAULT 'Client',
    expediteur_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expediteur_role TEXT NOT NULL CHECK (expediteur_role IN ('client', 'admin')),
    texte TEXT NOT NULL,
    lu BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour accélérer les requêtes de messagerie
CREATE INDEX IF NOT EXISTS idx_messages_restaurant_client ON public.messages(restaurant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at);

-- 2. Activation de la publication Realtime pour la table messages
-- Cela permet à l'application de recevoir les nouveaux messages instantanément
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

-- 3. Activation de la sécurité RLS (Row Level Security)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Les clients et admins connectés peuvent lire les messages qui les concernent
CREATE POLICY "Lecture des messages autorisée pour participants" ON public.messages
    FOR SELECT
    TO authenticated
    USING (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND admins.restaurant_id = messages.restaurant_id
        )
    );

-- Les clients et admins connectés peuvent envoyer des messages
CREATE POLICY "Insertion des messages pour participants" ON public.messages
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = expediteur_id);

-- Mise à jour du statut 'lu'
CREATE POLICY "Mise a jour du statut lu" ON public.messages
    FOR UPDATE
    TO authenticated
    USING (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND admins.restaurant_id = messages.restaurant_id
        )
    );
