-- ==============================================================================
-- RESTA : CONFIGURATION ULTRA-ROBUSTE DE LA TABLE DES MESSAGES & TEMPS RÉEL (REALTIME)
-- ==============================================================================
-- Exécutez ce script dans l'Éditeur SQL de votre tableau de bord Supabase :
-- (Dashboard Supabase > SQL Editor > New query > Run)

-- 1. Nettoyage préventif
DROP TABLE IF EXISTS public.messages CASCADE;

-- 2. Création de la table des messages
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL DEFAULT 1,
    client_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    client_nom TEXT DEFAULT 'Client',
    expediteur_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expediteur_role TEXT NOT NULL CHECK (expediteur_role IN ('client', 'admin')),
    texte TEXT NOT NULL,
    lu BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index de performance
CREATE INDEX IF NOT EXISTS idx_messages_restaurant_client ON public.messages(restaurant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_messages_client_id ON public.messages(client_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at);

-- 3. Activation du REPLICA IDENTITY FULL (requis pour Supabase Realtime)
ALTER TABLE public.messages REPLICA IDENTITY FULL;

-- 4. Publication Realtime pour la table messages
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
    END IF;
END $$;

-- 5. S'assurer que les administrateurs ont le droit de lire leur statut dans la table 'admins'
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins peuvent lire leur statut" ON public.admins;
CREATE POLICY "Admins peuvent lire leur statut" ON public.admins
    FOR SELECT
    TO authenticated
    USING (auth.uid() = user_id);

-- 6. Activation de la sécurité RLS sur 'messages'
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Lecture des messages autorisée pour participants" ON public.messages;
DROP POLICY IF EXISTS "Insertion des messages pour participants" ON public.messages;
DROP POLICY IF EXISTS "Mise a jour du statut lu" ON public.messages;

-- A) LECTURE :
-- - Les clients voient leurs propres messages (client_id = auth.uid())
-- - Les administrateurs voient les messages de leur restaurant (ou tous les messages si restaurant_id est NULL)
CREATE POLICY "Lecture des messages autorisée pour participants" ON public.messages
    FOR SELECT
    TO authenticated
    USING (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND (admins.restaurant_id IS NULL OR admins.restaurant_id::text = messages.restaurant_id::text)
        )
    );

-- B) INSERTION :
-- Un utilisateur connecté peut envoyer un message en son nom propre
CREATE POLICY "Insertion des messages pour participants" ON public.messages
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = expediteur_id);

-- C) MISE À JOUR DU STATUT 'LU' :
-- Le client ou l'administrateur peut marquer les messages reçus comme lus
CREATE POLICY "Mise a jour du statut lu" ON public.messages
    FOR UPDATE
    TO authenticated
    USING (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND (admins.restaurant_id IS NULL OR admins.restaurant_id::text = messages.restaurant_id::text)
        )
    )
    WITH CHECK (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND (admins.restaurant_id IS NULL OR admins.restaurant_id::text = messages.restaurant_id::text)
        )
    );
