-- ==============================================================================
-- RESTA : CRÉATION DE LA TABLE DES MESSAGES & ACTIVATION DU TEMPS RÉEL (REALTIME)
-- ==============================================================================
-- Exécutez ce script dans l'Éditeur SQL de votre tableau de bord Supabase
-- (Dashboard Supabase > SQL Editor > New query > Run)

-- 1. Nettoyage préventif au cas où la table a été créée avec un mauvais type
DROP TABLE IF EXISTS public.messages CASCADE;

-- 2. Création de la table des messages (restaurant_id en BIGINT compatible avec votre base)
CREATE TABLE public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    client_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    client_nom TEXT DEFAULT 'Client',
    expediteur_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expediteur_role TEXT NOT NULL CHECK (expediteur_role IN ('client', 'admin')),
    texte TEXT NOT NULL,
    lu BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour accélérer les requêtes de messagerie
CREATE INDEX IF NOT EXISTS idx_messages_restaurant_client ON public.messages(restaurant_id, client_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(created_at);

-- 3. Activation de la publication Realtime pour la table messages
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'messages'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
    END IF;
END $$;

-- 4. Activation de la sécurité RLS (Row Level Security)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Les participants peuvent lire les messages (avec cast explicite ::text pour éviter toute erreur de type)
CREATE POLICY "Lecture des messages autorisée pour participants" ON public.messages
    FOR SELECT
    TO authenticated
    USING (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND admins.restaurant_id::text = messages.restaurant_id::text
        )
    );

-- Les participants peuvent envoyer des messages
CREATE POLICY "Insertion des messages pour participants" ON public.messages
    FOR INSERT
    TO authenticated
    WITH CHECK (auth.uid() = expediteur_id);

-- Mise à jour du statut 'lu'
CREATE POLICY "Mise a jour du statut lu" ON public.messages
    FOR UPDATE
    TO authenticated
    USING (
        auth.uid() = client_id OR
        EXISTS (
            SELECT 1 FROM public.admins
            WHERE admins.user_id = auth.uid()
            AND admins.restaurant_id::text = messages.restaurant_id::text
        )
    );
